In [2]:
from util.GurobiOptimizer import GurobiOptimizer
import numpy as np

In [2]:
GurobiOptimizer = GurobiOptimizer()
solution = GurobiOptimizer.run_full_optimization()

Processing series: 100%|██████████| 153/153 [03:36<00:00,  1.42s/series]


In [ ]:
initial_demands, final_grid_demands, charging_demands, soc_t_v_s, optimal_objectives, optimization_times, mip_gaps, self_sufficiencies, pv_utilizations = solution

In [5]:
print(np.array(self_sufficiencies).mean(), np.array(pv_utilizations).mean())
print(np.array(self_sufficiencies).std(), np.array(pv_utilizations).std())

0.4569165745086894 0.9664461290009903
0.10280459572448873 0.030298334374897238


In [ ]:
# import matplotlib.pyplot as plt
# from pyparsing import col

# print(sum(charging_demand))
# print([round(float(i),2) for i in pv])
# print(len(pv))
# plt.figure(figsize=(12, 6))
# plt.step(range(len(initial_demand)), initial_demand , label='Initial Demand', where='post')
# plt.step(range(len(final_grid_demand)), final_grid_demand, label='Final Demand', color='black', where='post')
# plt.step(range(len(charging_demand)), [final_grid_demand[i] - charging_demand[i] for i in range(len(charging_demand))], label='Charging Demand', color='orange', where='post')
# plt.xlabel('Time Step')
# plt.ylabel('Demand (kW)')
# plt.title('Demand Comparison')
# plt.legend()
# plt.grid(True)
# plt.show()

NameError: name 'charging_demand' is not defined

PLOT

In [1]:
from util.GurobiOptimizer import GurobiOptimizer
import numpy as np

GurobiOptimizer = GurobiOptimizer()
solution = GurobiOptimizer.run_full_immediate_charging()

Processing series (immediate): 100%|██████████| 153/153 [00:05<00:00, 25.91series/s]


In [13]:
initial_demands, final_grid_demands, charging_demands, soc_t_v_s, total_costs, self_sufficiencies, pv_utilizations = solution

In [14]:
RESULTS_PATH = "/home/lisa4090/Documents/GitHub/V2B_Optimization_with_AI_on_BSS/optimization/output/V1_WL48_PV400"
RESULTS_PATH_IMMEDIATE = "/home/lisa4090/Documents/GitHub/V2B_Optimization_with_AI_on_BSS/optimization/output_immediate_V1_WL48_PV400"

pv_utilizations = np.load(RESULTS_PATH + '/pv_utilizations.npy')
self_sufficiencies = np.load(RESULTS_PATH + '/self_sufficiencies.npy')
charging_demands = np.load(RESULTS_PATH + '/charging_demands.npy')
soc_t_v = np.load(RESULTS_PATH + '/soc_t_v.npy')

pv_utilizations_immediate = np.load(RESULTS_PATH_IMMEDIATE + '/pv_utilizations.npy')
self_sufficiencies_immediate = np.load(RESULTS_PATH_IMMEDIATE + '/self_sufficiencies.npy')
charging_demands_immediate = np.load(RESULTS_PATH_IMMEDIATE + '/charging_demands.npy')


In [15]:
# charging_demands.sum(axis=1)
soc_t_v.shape

(153, 199, 48)

In [24]:
soc_t_v_s[0][:,50].round(2)

array([0.72, 0.72, 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 ,
       0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 ,
       0.9 , 0.9 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  ])

In [25]:
soc_t_v[0][50].round(2)

array([0.72, 0.72, 0.72, 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 ,
       0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.9 , 0.9 , 0.9 , 0.9 ,
       0.9 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 ,
       0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 , 0.2 ,
       0.2 , 0.2 , 0.2 , 0.2 ])

In [18]:
charging_demands_immediate.sum()

np.float64(14043.45)

In [19]:
np.array(charging_demands).sum()

np.float64(3000.2333261672557)

In [8]:
np.array([round(i,2) for i in charging_demands_immediate[0]])

array([14.  , 11.33,  0.  ,  0.  ,  9.6 ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.95,  2.98,  6.78, 14.  ,  2.43,  0.  ,  0.  ,
        0.  ,  0.65,  1.83,  0.  ,  0.  ,  7.1 ,  3.82,  0.  ,  0.  ,
        0.62,  7.47,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  2.05,  0.  ,
        0.62,  1.15,  0.62,  0.6 ,  5.07,  5.27,  0.  ,  0.  ,  5.63,
        0.  ,  0.  ,  0.  ])